routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});


Route::get('/test', function () {
    echo route('deviceRegisteration');
});

Route::post('/newsFilter/add_news', 'NewsFilter@add_news');

Route::post('/news/select_news_by_id', 'NewsController@SelectNewsById');

Route::resource('newsFilter', 'NewsFilter@index');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('pages', 'PageController');

Route::resource('users', 'UsersController');

Route::resource('admins', 'AdminController');

Route::resource('adminUserTypes', 'AdminUserTypeController');

Route::resource('adminUserLogs', 'AdminUserLogController');

Route::resource('adminLogTypes', 'AdminLogTypeController');

Route::resource('countries', 'CountryController');

Route::resource('locations', 'LocationController');

Route::resource('locationServices', 'LocationServiceController');

Route::resource('news', 'NewsController');

Route::resource('newsCategories', 'NewsCategoryController');

Route::resource('newsSources', 'NewsSourceController');

Route::resource('paymentMethodCountries', 'PaymentMethodCountryController');

Route::resource('paymentMethods', 'PaymentMethodController');

Route::resource('serviceApis', 'ServiceApiController');

Route::resource('serviceMetaDatas', 'ServiceMetaDataController');

Route::resource('serviceMetaKeys', 'ServiceMetaKeyController');

Route::resource('services', 'ServiceController');

Route::resource('serviceBookeds', 'ServiceBookedController');

Route::resource('transactions', 'TransactionController');

Route::resource('userLogs', 'UserLogController');

Route::resource('feedback', 'FeedbackController');

Route::resource('promocode', 'PromoCodeController');

Route::resource('promocode_service_map', 'PromocodeServiceMapController');

Route::resource('hotel_refund', 'HotelRefundController');

Route::resource('user_refund', 'UserRefundController');


//Route::post('store', ['as' => 'users.store', 'uses' => 'UsersController@store']);

//Route::get('store','\App\Http\Controllers\UsersController@store');
Route::resource('notification', 'NotificationController');


Route::resource('devices', 'DeviceController');
Route::get('razorpay/test', 'RazorPayTestController@testform');
Route::post('razorpay/test', 'RazorPayTestController@submitForm');

Route::any('hotel_refund/refund', ['as' => 'full_refund', 'HotelRefundController@index']);

Route::any('hotel_refund/refund/{id}', 'HotelRefundController@refund');

Route::any('hotel_refund/partial_refund/',  'HotelRefundController@partialRefund');

resources/views/admins/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Admin
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        @include('flash::message')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'admins.store']) !!}

                    @include('admins.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admins/datatables_actions.blade.php
{!! Form::open(['route' => ['admins.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('admins.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('admins.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/admins/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Admin
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::model($admin, ['route' => ['admins.update', $admin->id], 'method' => 'patch']) !!}

                    @include('admins.edit_fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admins/edit_fields.blade.php
<!-- User Type Field -->
{{--<div class="form-group col-sm-12">--}}
{{--{!! Form::label('user_type', 'User Type:') !!}--}}
{{--{!! Form::number('user_type', null, ['class' => 'form-control']) !!}--}}
{{--</div>--}}

<!-- First Name Field -->
<div class="form-group col-sm-12">

    {!! Form::label('first_name', 'First Name:') !!}
    {!! Form::text('first_name', old('first_name') , ['class' => 'form-control']) !!}
</div>

<!-- Last Name Field -->
<div class="form-group col-sm-12">
    {!! Form::label('last_name', 'Last Name:') !!}
    {!! Form::text('last_name', null, ['class' => 'form-control']) !!}
</div>
<!-- Location Field -->
<div class="form-group col-sm-12">
    {!! Form::label('location', 'Location:') !!}
    {!! Form::text('location', null, ['class' => 'form-control']) !!}
</div>

<!-- Mobile Field -->
<div class="form-group col-sm-12">
    {!! Form::label('mobile', 'Mobile:') !!}
    {!! Form::text('mobile', null, ['class' => 'form-control']) !!}
</div>
<!-- Email Field -->
<div class="form-group col-sm-12">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::email('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Password Field -->
<div class="form-group col-sm-12">
    {!! Form::label('password', 'Password:') !!}
    {!! Form::password('password', ['class' => 'form-control']) !!}
</div>

<!-- Job Role Field -->
<div class="form-group col-sm-12 col-lg-12 country_selectbox">
    {!! Form::label('Privilege', 'Privilege:') !!}
    {!! Form::text('job_role', null, ['class' => 'form-control']) !!}
</div>
<div class="form-group col-sm-12 col-lg-12 country_selectbox">
    {!! Form::label('Privilege', 'Privilege:') !!}
    {{Form::select('user_type',$userType,$selectedAdminType,array('class'=>'form-control','id'=>'user_type','name'=>'user_type'))}}
</div>
<div class="form-group col-sm-12 radio_isactive ">
    {!! Form::label('is_active', ' Is Active:') !!}<br>
    {!! Form::radio('is_active', 1,true).'Active' !!}
    {!! Form::radio('is_active', 0,false).'Inactive' !!}
</div>
<!-- Activation Code Field -->
{{--<div class="form-group col-sm-6">--}}
{{--{!! Form::label('activation_code', 'Activation Code:') !!}--}}
{{--{!! Form::text('activation_code', null, ['class' => 'form-control']) !!}--}}
{{--</div>--}}

<!-- Remember Token Field -->
{{--<div class="form-group col-sm-6">--}}
{{--{!! Form::label('remember_token', 'Remember Token:') !!}--}}
{{--{!! Form::text('remember_token', null, ['class' => 'form-control']) !!}--}}
{{--</div>--}}

<!-- Created By Field -->
{{--<div class="form-group col-sm-6">--}}
{{--{!! Form::label('created_by', 'Created By:') !!}--}}
{{--{!! Form::number('created_by', null, ['class' => 'form-control']) !!}--}}
{{--</div>--}}

<!-- Updated By Field -->
{{--<div class="form-group col-sm-6">--}}
{{--{!! Form::label('updated_by', 'Updated By:') !!}--}}
{{--{!! Form::number('updated_by', null, ['class' => 'form-control']) !!}--}}
{{--</div>--}}

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('admins.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/admins/fields.blade.php
<!-- User Type Field -->
{{--<div class="form-group col-sm-12">--}}
{{--{!! Form::label('user_type', 'User Type:') !!}--}}
{{--{!! Form::number('user_type', null, ['class' => 'form-control']) !!}--}}
{{--</div>--}}

<!-- First Name Field -->
<div class="form-group col-sm-12">

    {!! Form::label('first_name', 'First Name:') !!}
    {!! Form::text('first_name', old('first_name') , ['class' => 'form-control']) !!}
</div>

<!-- Last Name Field -->
<div class="form-group col-sm-12">
    {!! Form::label('last_name', 'Last Name:') !!}
    {!! Form::text('last_name', null, ['class' => 'form-control']) !!}
</div>
<!-- Location Field -->
<div class="form-group col-sm-12">
    {!! Form::label('location', 'Location:') !!}
    {!! Form::text('location', null, ['class' => 'form-control']) !!}
</div>

<!-- Mobile Field -->
<div class="form-group col-sm-12">
    {!! Form::label('mobile', 'Mobile:') !!}
    {!! Form::text('mobile', null, ['class' => 'form-control']) !!}
</div>
<!-- Email Field -->
<div class="form-group col-sm-12">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::email('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Password Field -->
<div class="form-group col-sm-12">
    {!! Form::label('password', 'Password:') !!}
    {!! Form::password('password', ['class' => 'form-control']) !!}
</div>

<!-- Job Role Field -->
<div class="form-group col-sm-12 col-lg-12 country_selectbox">
    {!! Form::label('Privilege', 'Privilege:') !!}
    {!! Form::text('job_role', null, ['class' => 'form-control']) !!}
</div>
<!-- Admin type Field -->
<div class="form-group col-sm-12 col-lg-12 country_selectbox">
    {!! Form::label('Privilege', 'Privilege:') !!}
    {{Form::select('user_type',$userType,$selectedAdminType,array('class'=>'form-control','id'=>'user_type','name'=>'user_type'))}}
</div>
<div class="form-group col-sm-12 radio_isactive ">
    {!! Form::label('is_active', ' Is Active:') !!}<br>
    {!! Form::radio('is_active', 1,true).'Active' !!}
    {!! Form::radio('is_active', 0,false).'Inactive' !!}
</div>
<!-- Activation Code Field -->
{{--<div class="form-group col-sm-6">--}}
{{--{!! Form::label('activation_code', 'Activation Code:') !!}--}}
{{--{!! Form::text('activation_code', null, ['class' => 'form-control']) !!}--}}
{{--</div>--}}

<!-- Remember Token Field -->
{{--<div class="form-group col-sm-6">--}}
{{--{!! Form::label('remember_token', 'Remember Token:') !!}--}}
{{--{!! Form::text('remember_token', null, ['class' => 'form-control']) !!}--}}
{{--</div>--}}

<!-- Created By Field -->
{{--<div class="form-group col-sm-6">--}}
{{--{!! Form::label('created_by', 'Created By:') !!}--}}
{{--{!! Form::number('created_by', null, ['class' => 'form-control']) !!}--}}
{{--</div>--}}

<!-- Updated By Field -->
{{--<div class="form-group col-sm-6">--}}
{{--{!! Form::label('updated_by', 'Updated By:') !!}--}}
{{--{!! Form::number('updated_by', null, ['class' => 'form-control']) !!}--}}
{{--</div>--}}

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('admins.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/admins/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Admins</h1>
        <h1 class="pull-right">
            <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px"
               href="{!! route('admins.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                @include('admins.table')
            </div>
        </div>
    </div>
@endsection

resources/views/admins/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Admin
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('admins.show_fields')
                    <a href="{!! route('admins.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admins/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $admin->id !!}</p>
</div>

<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', 'Email:') !!}
    <p>{!! $admin->email !!}</p>
</div>

<!-- Password Field -->
{{--<div class="form-group">--}}
{{--{!! Form::label('password', 'Password:') !!}--}}
{{--<p>{!! $admin->password !!}</p>--}}
{{--</div>--}}

<!-- User Type Field -->
<div class="form-group">
    {!! Form::label('user_type', 'User Type:') !!}

    <p>
        {{ ucfirst($admin->adminUserType->type) }}
    </p>
</div>
<!-- First Name Field -->
<div class="form-group">
    {!! Form::label('first_name', 'First Name:') !!}
    <p>{!! $admin->first_name !!}</p>
</div>

<!-- Last Name Field -->
<div class="form-group">
    {!! Form::label('last_name', 'Last Name:') !!}
    <p>{!! $admin->last_name !!}</p>
</div>

<!-- Mobile Field -->
<div class="form-group">
    {!! Form::label('mobile', 'Mobile:') !!}
    <p>{!! $admin->mobile !!}</p>
</div>

<!-- Job Role Field -->
<div class="form-group">
    {!! Form::label('job_role', 'Job Role:') !!}
    <p>{!! $admin->job_role !!}</p>
</div>

<!-- Is Active Field -->
<div class="form-group">
    {!! Form::label('is_active', 'Is Active:') !!}
    @if($admin->is_active==1)
        <p class="label label-primary">{!! 'Yes' !!}</p>
    @else
        <p class="label label-danger">{!! 'No' !!}</p>
    @endif
</div>
<!-- Activation Code Field -->
{{--<div class="form-group">--}}
{{--{!! Form::label('activation_code', 'Activation Code:') !!}--}}
{{--<p>{!! $admin->activation_code !!}</p>--}}
{{--</div>--}}

{{--<!-- Remember Token Field -->--}}
{{--<div class="form-group">--}}
{{--{!! Form::label('remember_token', 'Remember Token:') !!}--}}
{{--<p>{!! $admin->remember_token !!}</p>--}}
{{--</div>--}}

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $admin->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $admin->updated_at !!}</p>
</div>

<!-- Created By Field -->
{{--<div class="form-group">--}}
{{--{!! Form::label('created_by', 'Created By:') !!}--}}
{{--<p>{!! $admin->created_by !!}</p>--}}
{{--</div>--}}

<!-- Updated By Field -->
{{--<div class="form-group">--}}
{{--{!! Form::label('updated_by', 'Updated By:') !!}--}}
{{--<p>{!! $admin->updated_by !!}</p>--}}
{{--</div>--}}

<!-- Deleted At Field -->
{{--<div class="form-group">--}}
{{--{!! Form::label('deleted_at', 'Deleted At:') !!}--}}
{{--<p>{!! $admin->deleted_at !!}</p>--}}
{{--</div>--}}

resources/views/admins/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection