routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});


Route::get('/test', function () {
    echo route('deviceRegisteration');
});

Route::post('/newsFilter/add_news', 'NewsFilter@add_news');

Route::post('/news/select_news_by_id', 'NewsController@SelectNewsById');

Route::resource('newsFilter', 'NewsFilter@index');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('pages', 'PageController');

Route::resource('users', 'UsersController');

Route::resource('admins', 'AdminController');

Route::resource('adminUserTypes', 'AdminUserTypeController');

Route::resource('adminUserLogs', 'AdminUserLogController');

Route::resource('adminLogTypes', 'AdminLogTypeController');

Route::resource('countries', 'CountryController');

Route::resource('locations', 'LocationController');

Route::resource('locationServices', 'LocationServiceController');

Route::resource('news', 'NewsController');

Route::resource('newsCategories', 'NewsCategoryController');

Route::resource('newsSources', 'NewsSourceController');

Route::resource('paymentMethodCountries', 'PaymentMethodCountryController');

Route::resource('paymentMethods', 'PaymentMethodController');

Route::resource('serviceApis', 'ServiceApiController');

Route::resource('serviceMetaDatas', 'ServiceMetaDataController');

Route::resource('serviceMetaKeys', 'ServiceMetaKeyController');

Route::resource('services', 'ServiceController');

Route::resource('serviceBookeds', 'ServiceBookedController');

Route::resource('transactions', 'TransactionController');

Route::resource('userLogs', 'UserLogController');

Route::resource('feedback', 'FeedbackController');

Route::resource('promocode', 'PromoCodeController');

Route::resource('promocode_service_map', 'PromocodeServiceMapController');

Route::resource('hotel_refund', 'HotelRefundController');

Route::resource('user_refund', 'UserRefundController');


//Route::post('store', ['as' => 'users.store', 'uses' => 'UsersController@store']);

//Route::get('store','\App\Http\Controllers\UsersController@store');
Route::resource('notification', 'NotificationController');


Route::resource('devices', 'DeviceController');
Route::get('razorpay/test', 'RazorPayTestController@testform');
Route::post('razorpay/test', 'RazorPayTestController@submitForm');

Route::any('hotel_refund/refund', ['as' => 'full_refund', 'HotelRefundController@index']);

Route::any('hotel_refund/refund/{id}', 'HotelRefundController@refund');

Route::any('hotel_refund/partial_refund/',  'HotelRefundController@partialRefund');

app/Models/ServiceMetaData.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class ServiceMetaData
 *
 * @package App\Models
 * @version February 24, 2017, 12:00 pm UTC
 */
class ServiceMetaData extends Model
{
	use SoftDeletes;

	public $table = 'service_meta_data';

	const CREATED_AT = 'created_at';
	const UPDATED_AT = 'updated_at';


	protected $dates = ['deleted_at'];


	public $fillable = [
		'meta_key_id' ,
		'booked_id' ,
		'value'
	];

	/**
	 * The attributes that should be casted to native types.
	 *
	 * @var array
	 */
	protected $casts = [
		'id' => 'integer' ,
		'meta_key_id' => 'integer' ,
		'booked_id' => 'integer' ,
		'value' => 'string'
	];

	/**
	 * Validation rules
	 *
	 * @var array
	 */
	public static $rules = [

	];

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 **/
	public function servicesBooked ()
	{
		return $this->belongsTo (\App\Models\ServicesBooked::class);
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 **/
	public function serviceMetaKey ()
	{
		return $this->belongsTo (\App\Models\ServiceMetaKey::class);
	}
}

app/Http/Controllers/ServiceMetaDataController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\ServiceMetaDataDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateServiceMetaDataRequest;
use App\Http\Requests\UpdateServiceMetaDataRequest;
use App\Repositories\ServiceMetaDataRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class ServiceMetaDataController extends AppBaseController
{
	/** @var  ServiceMetaDataRepository */
	private $serviceMetaDataRepository;

	public function __construct (ServiceMetaDataRepository $serviceMetaDataRepo)
	{
		$this->serviceMetaDataRepository = $serviceMetaDataRepo;
	}

	/**
	 * Display a listing of the ServiceMetaData.
	 *
	 * @param ServiceMetaDataDataTable $serviceMetaDataDataTable
	 *
	 * @return Response
	 */
	public function index (ServiceMetaDataDataTable $serviceMetaDataDataTable)
	{
		return $serviceMetaDataDataTable->render ('service_meta_datas.index');
	}

	/**
	 * Show the form for creating a new ServiceMetaData.
	 *
	 * @return Response
	 */
	public function create ()
	{
		return view ('service_meta_datas.create');
	}

	/**
	 * Store a newly created ServiceMetaData in storage.
	 *
	 * @param CreateServiceMetaDataRequest $request
	 *
	 * @return Response
	 */
	public function store (CreateServiceMetaDataRequest $request)
	{
		$input = $request->all ();

		$serviceMetaData = $this->serviceMetaDataRepository->create ($input);

		Flash::success ('Service Meta Data saved successfully.');

		return redirect (route ('serviceMetaDatas.index'));
	}

	/**
	 * Display the specified ServiceMetaData.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function show ($id)
	{
		$serviceMetaData = $this->serviceMetaDataRepository->findWithoutFail ($id);

		if (empty($serviceMetaData)) {
			Flash::error ('Service Meta Data not found');

			return redirect (route ('serviceMetaDatas.index'));
		}

		return view ('service_meta_datas.show')->with ('serviceMetaData' , $serviceMetaData);
	}

	/**
	 * Show the form for editing the specified ServiceMetaData.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function edit ($id)
	{
		$serviceMetaData = $this->serviceMetaDataRepository->findWithoutFail ($id);

		if (empty($serviceMetaData)) {
			Flash::error ('Service Meta Data not found');

			return redirect (route ('serviceMetaDatas.index'));
		}

		return view ('service_meta_datas.edit')->with ('serviceMetaData' , $serviceMetaData);
	}

	/**
	 * Update the specified ServiceMetaData in storage.
	 *
	 * @param  int                         $id
	 * @param UpdateServiceMetaDataRequest $request
	 *
	 * @return Response
	 */
	public function update ($id , UpdateServiceMetaDataRequest $request)
	{
		$serviceMetaData = $this->serviceMetaDataRepository->findWithoutFail ($id);

		if (empty($serviceMetaData)) {
			Flash::error ('Service Meta Data not found');

			return redirect (route ('serviceMetaDatas.index'));
		}

		$serviceMetaData = $this->serviceMetaDataRepository->update ($request->all () , $id);

		Flash::success ('Service Meta Data updated successfully.');

		return redirect (route ('serviceMetaDatas.index'));
	}

	/**
	 * Remove the specified ServiceMetaData from storage.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function destroy ($id)
	{
		$serviceMetaData = $this->serviceMetaDataRepository->findWithoutFail ($id);

		if (empty($serviceMetaData)) {
			Flash::error ('Service Meta Data not found');

			return redirect (route ('serviceMetaDatas.index'));
		}

		$this->serviceMetaDataRepository->delete ($id);

		Flash::success ('Service Meta Data deleted successfully.');

		return redirect (route ('serviceMetaDatas.index'));
	}
}

resources/views/service_meta_datas/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Service Meta Data
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'serviceMetaDatas.store']) !!}

                    @include('service_meta_datas.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/service_meta_datas/datatables_actions.blade.php
{!! Form::open(['route' => ['serviceMetaDatas.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('serviceMetaDatas.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('serviceMetaDatas.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/service_meta_datas/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Service Meta Data
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::model($serviceMetaData, ['route' => ['serviceMetaDatas.update', $serviceMetaData->id], 'method' => 'patch']) !!}

                    @include('service_meta_datas.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/service_meta_datas/fields.blade.php
<!-- Meta Key Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('meta_key_id', 'Meta Key Id:') !!}
    {!! Form::number('meta_key_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Booked Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('booked_id', 'Booked Id:') !!}
    {!! Form::number('booked_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Value Field -->
<div class="form-group col-sm-6">
    {!! Form::label('value', 'Value:') !!}
    {!! Form::text('value', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('serviceMetaDatas.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/service_meta_datas/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Service Meta Datas</h1>
        <h1 class="pull-right">
            <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px"
               href="{!! route('serviceMetaDatas.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                @include('service_meta_datas.table')
            </div>
        </div>
    </div>
@endsection

resources/views/service_meta_datas/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Service Meta Data
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('service_meta_datas.show_fields')
                    <a href="{!! route('serviceMetaDatas.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/service_meta_datas/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $serviceMetaData->id !!}</p>
</div>

<!-- Meta Key Id Field -->
<div class="form-group">
    {!! Form::label('meta_key_id', 'Meta Key Id:') !!}
    <p>{!! $serviceMetaData->meta_key_id !!}</p>
</div>

<!-- Booked Id Field -->
<div class="form-group">
    {!! Form::label('booked_id', 'Booked Id:') !!}
    <p>{!! $serviceMetaData->booked_id !!}</p>
</div>

<!-- Value Field -->
<div class="form-group">
    {!! Form::label('value', 'Value:') !!}
    <p>{!! $serviceMetaData->value !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $serviceMetaData->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $serviceMetaData->updated_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $serviceMetaData->deleted_at !!}</p>
</div>

resources/views/service_meta_datas/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection