routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});


Route::get('/test', function () {
    echo route('deviceRegisteration');
});

Route::post('/newsFilter/add_news', 'NewsFilter@add_news');

Route::post('/news/select_news_by_id', 'NewsController@SelectNewsById');

Route::resource('newsFilter', 'NewsFilter@index');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('pages', 'PageController');

Route::resource('users', 'UsersController');

Route::resource('admins', 'AdminController');

Route::resource('adminUserTypes', 'AdminUserTypeController');

Route::resource('adminUserLogs', 'AdminUserLogController');

Route::resource('adminLogTypes', 'AdminLogTypeController');

Route::resource('countries', 'CountryController');

Route::resource('locations', 'LocationController');

Route::resource('locationServices', 'LocationServiceController');

Route::resource('news', 'NewsController');

Route::resource('newsCategories', 'NewsCategoryController');

Route::resource('newsSources', 'NewsSourceController');

Route::resource('paymentMethodCountries', 'PaymentMethodCountryController');

Route::resource('paymentMethods', 'PaymentMethodController');

Route::resource('serviceApis', 'ServiceApiController');

Route::resource('serviceMetaDatas', 'ServiceMetaDataController');

Route::resource('serviceMetaKeys', 'ServiceMetaKeyController');

Route::resource('services', 'ServiceController');

Route::resource('serviceBookeds', 'ServiceBookedController');

Route::resource('transactions', 'TransactionController');

Route::resource('userLogs', 'UserLogController');

Route::resource('feedback', 'FeedbackController');

Route::resource('promocode', 'PromoCodeController');

Route::resource('promocode_service_map', 'PromocodeServiceMapController');

Route::resource('hotel_refund', 'HotelRefundController');

Route::resource('user_refund', 'UserRefundController');


//Route::post('store', ['as' => 'users.store', 'uses' => 'UsersController@store']);

//Route::get('store','\App\Http\Controllers\UsersController@store');
Route::resource('notification', 'NotificationController');


Route::resource('devices', 'DeviceController');
Route::get('razorpay/test', 'RazorPayTestController@testform');
Route::post('razorpay/test', 'RazorPayTestController@submitForm');

Route::any('hotel_refund/refund', ['as' => 'full_refund', 'HotelRefundController@index']);

Route::any('hotel_refund/refund/{id}', 'HotelRefundController@refund');

Route::any('hotel_refund/partial_refund/',  'HotelRefundController@partialRefund');

app/Models/PaymentMethodCountry.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class PaymentMethodCountry
 *
 * @package App\Models
 * @version February 24, 2017, 11:54 am UTC
 */
class PaymentMethodCountry extends Model
{
	use SoftDeletes;

	public $table = 'payment_method_countries';

	const CREATED_AT = 'created_at';
	const UPDATED_AT = 'updated_at';


	protected $dates = ['deleted_at'];


	public $fillable = [
		'gateway_id' ,
		'country_id' ,
		'created_by' ,
		'updated_by'
	];

	/**
	 * The attributes that should be casted to native types.
	 *
	 * @var array
	 */
	protected $casts = [
		'id' => 'integer' ,
		'gateway_id' => 'integer' ,
		'country_id' => 'integer' ,
		'created_by' => 'integer' ,
		'updated_by' => 'integer'
	];

	/**
	 * Validation rules
	 *
	 * @var array
	 */
	public static $rules = [

	];

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 **/
	public function country ()
	{
		return $this->belongsTo (\App\Models\Country::class);
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 **/
	public function adminUser ()
	{
		return $this->belongsTo (\App\Models\Admin::class);
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 **/
	public function paymentMethod ()
	{
		return $this->belongsTo (\App\Models\PaymentMethod::class);
	}


}

app/Http/Controllers/PaymentMethodCountryController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\PaymentMethodCountryDataTable;
use App\Http\Requests;
use App\Http\Requests\CreatePaymentMethodCountryRequest;
use App\Http\Requests\UpdatePaymentMethodCountryRequest;
use App\Repositories\PaymentMethodCountryRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class PaymentMethodCountryController extends AppBaseController
{
	/** @var  PaymentMethodCountryRepository */
	private $paymentMethodCountryRepository;

	public function __construct (PaymentMethodCountryRepository $paymentMethodCountryRepo)
	{
		$this->paymentMethodCountryRepository = $paymentMethodCountryRepo;
	}

	/**
	 * Display a listing of the PaymentMethodCountry.
	 *
	 * @param PaymentMethodCountryDataTable $paymentMethodCountryDataTable
	 *
	 * @return Response
	 */
	public function index (PaymentMethodCountryDataTable $paymentMethodCountryDataTable)
	{
		return $paymentMethodCountryDataTable->render ('payment_method_countries.index');
	}

	/**
	 * Show the form for creating a new PaymentMethodCountry.
	 *
	 * @return Response
	 */
	public function create ()
	{
		return view ('payment_method_countries.create');
	}

	/**
	 * Store a newly created PaymentMethodCountry in storage.
	 *
	 * @param CreatePaymentMethodCountryRequest $request
	 *
	 * @return Response
	 */
	public function store (CreatePaymentMethodCountryRequest $request)
	{
		$input = $request->all ();

		$paymentMethodCountry = $this->paymentMethodCountryRepository->create ($input);

		Flash::success ('Payment Method Country saved successfully.');

		return redirect (route ('paymentMethodCountries.index'));
	}

	/**
	 * Display the specified PaymentMethodCountry.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function show ($id)
	{
		$paymentMethodCountry = $this->paymentMethodCountryRepository->findWithoutFail ($id);

		if (empty($paymentMethodCountry)) {
			Flash::error ('Payment Method Country not found');

			return redirect (route ('paymentMethodCountries.index'));
		}

		return view ('payment_method_countries.show')->with ('paymentMethodCountry' , $paymentMethodCountry);
	}

	/**
	 * Show the form for editing the specified PaymentMethodCountry.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function edit ($id)
	{
		$paymentMethodCountry = $this->paymentMethodCountryRepository->findWithoutFail ($id);

		if (empty($paymentMethodCountry)) {
			Flash::error ('Payment Method Country not found');

			return redirect (route ('paymentMethodCountries.index'));
		}

		return view ('payment_method_countries.edit')->with ('paymentMethodCountry' , $paymentMethodCountry);
	}

	/**
	 * Update the specified PaymentMethodCountry in storage.
	 *
	 * @param  int                              $id
	 * @param UpdatePaymentMethodCountryRequest $request
	 *
	 * @return Response
	 */
	public function update ($id , UpdatePaymentMethodCountryRequest $request)
	{
		$paymentMethodCountry = $this->paymentMethodCountryRepository->findWithoutFail ($id);

		if (empty($paymentMethodCountry)) {
			Flash::error ('Payment Method Country not found');

			return redirect (route ('paymentMethodCountries.index'));
		}

		$paymentMethodCountry = $this->paymentMethodCountryRepository->update ($request->all () , $id);

		Flash::success ('Payment Method Country updated successfully.');

		return redirect (route ('paymentMethodCountries.index'));
	}

	/**
	 * Remove the specified PaymentMethodCountry from storage.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function destroy ($id)
	{
		$paymentMethodCountry = $this->paymentMethodCountryRepository->findWithoutFail ($id);

		if (empty($paymentMethodCountry)) {
			Flash::error ('Payment Method Country not found');

			return redirect (route ('paymentMethodCountries.index'));
		}

		$this->paymentMethodCountryRepository->delete ($id);

		Flash::success ('Payment Method Country deleted successfully.');

		return redirect (route ('paymentMethodCountries.index'));
	}
}

resources/views/payment_method_countries/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Payment Method Country
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'paymentMethodCountries.store']) !!}

                    @include('payment_method_countries.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/payment_method_countries/datatables_actions.blade.php
{!! Form::open(['route' => ['paymentMethodCountries.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('paymentMethodCountries.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    {{--<a href="{{ route('paymentMethodCountries.edit', $id) }}" class='btn btn-default btn-xs'>--}}
    {{--<i class="glyphicon glyphicon-edit"></i>--}}
    {{--</a>--}}
    {{--{!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [--}}
    {{--'type' => 'submit',--}}
    {{--'class' => 'btn btn-danger btn-xs',--}}
    {{--'onclick' => "return confirm('Are you sure?')"--}}
    {{--]) !!}--}}
</div>
{!! Form::close() !!}

resources/views/payment_method_countries/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Payment Method Country
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::model($paymentMethodCountry, ['route' => ['paymentMethodCountries.update', $paymentMethodCountry->id], 'method' => 'patch']) !!}

                    @include('payment_method_countries.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/payment_method_countries/fields.blade.php
<!-- Gateway Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('gateway_id', 'Gateway Id:') !!}
    {!! Form::number('gateway_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Country Id Field -->


<div class="form-group col-sm-6">
    {!! Form::label('country_id', 'Country Id:') !!}
    {!! Form::number('country_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Created By Field -->
<div class="form-group col-sm-6">
    {!! Form::label('created_by', 'Created By:') !!}
    {!! Form::number('created_by', null, ['class' => 'form-control']) !!}
</div>

<!-- Updated By Field -->
<div class="form-group col-sm-6">
    {!! Form::label('updated_by', 'Updated By:') !!}
    {!! Form::number('updated_by', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('paymentMethodCountries.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/payment_method_countries/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Payment Method Countries</h1>
        <h1 class="pull-right">
            <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px"
               href="{!! route('paymentMethodCountries.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                @include('payment_method_countries.table')
            </div>
        </div>
    </div>
@endsection

resources/views/payment_method_countries/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Payment Method Country
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('payment_method_countries.show_fields')
                    <a href="{!! route('paymentMethodCountries.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/payment_method_countries/show_fields.blade.php
<?php
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
$gateway_id = $paymentMethodCountry->gateway_id;
$country = DB::table ('payment_method_countries')
        ->join ('payment_methods' , 'payment_method_countries.gateway_id' , '=' , 'payment_methods.id')
        ->join ('countries' , 'countries.id' , '=' , 'payment_method_countries.country_id')
        ->join ('admin_users' , 'admin_users.id' , '=' , 'payment_method_countries.updated_by')
        ->where ('payment_method_countries.gateway_id' , '=' , $gateway_id)
        ->select ('payment_method_countries.*' , 'payment_methods.*' , 'admin_users.*' , 'countries.*')
        ->get ();
?>
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $paymentMethodCountry->id !!}</p>
</div>

<!-- Gateway Id Field -->
<div class="form-group">
    {!! Form::label('gateway_id', 'Gateway Name:') !!}
    <p>
        <?php
        echo $country[0]->gateway_name;
        ?>
    </p>
</div>

<!-- Country Id Field -->


<div class="form-group">
    {!! Form::label('country_id', 'Countries:') !!}
    <p>
        <?php
        $i = 1;
        $count = count ($country);
        foreach ($country as $key => $val) {
            if ($i != 3) {
                $comma = ", ";
            } else {
                $comma = "";

            }
            echo $val->name . $comma;
            $i++;
        }
        ?>
    </p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $paymentMethodCountry->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $paymentMethodCountry->updated_at !!}</p>
</div>

<!-- Created By Field -->
{{--<div class="form-group">--}}
{{--{!! Form::label('created_by', 'Created By:') !!}--}}
{{--<p> {{$country[0]->first_name.' '.$country[0]->last_name}}--}}

{{--{!! $paymentMethodCountry->created_by !!}</p>--}}
{{--</div>--}}

<!-- Updated By Field -->
<div class="form-group">
    {!! Form::label('updated_by', 'Updated By:') !!}
    <p>{{$country[0]->first_name.' '.$country[0]->last_name}}
    </p>
</div>

<!-- Deleted At Field -->
{{--<div class="form-group">--}}
{{--{!! Form::label('deleted_at', 'Deleted At:') !!}--}}
{{--<p>{!! $paymentMethodCountry->deleted_at !!}</p>--}}
{{--</div>--}}

resources/views/payment_method_countries/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection