routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});


Route::get('/test', function () {
    echo route('deviceRegisteration');
});

Route::post('/newsFilter/add_news', 'NewsFilter@add_news');

Route::post('/news/select_news_by_id', 'NewsController@SelectNewsById');

Route::resource('newsFilter', 'NewsFilter@index');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('pages', 'PageController');

Route::resource('users', 'UsersController');

Route::resource('admins', 'AdminController');

Route::resource('adminUserTypes', 'AdminUserTypeController');

Route::resource('adminUserLogs', 'AdminUserLogController');

Route::resource('adminLogTypes', 'AdminLogTypeController');

Route::resource('countries', 'CountryController');

Route::resource('locations', 'LocationController');

Route::resource('locationServices', 'LocationServiceController');

Route::resource('news', 'NewsController');

Route::resource('newsCategories', 'NewsCategoryController');

Route::resource('newsSources', 'NewsSourceController');

Route::resource('paymentMethodCountries', 'PaymentMethodCountryController');

Route::resource('paymentMethods', 'PaymentMethodController');

Route::resource('serviceApis', 'ServiceApiController');

Route::resource('serviceMetaDatas', 'ServiceMetaDataController');

Route::resource('serviceMetaKeys', 'ServiceMetaKeyController');

Route::resource('services', 'ServiceController');

Route::resource('serviceBookeds', 'ServiceBookedController');

Route::resource('transactions', 'TransactionController');

Route::resource('userLogs', 'UserLogController');

Route::resource('feedback', 'FeedbackController');

Route::resource('promocode', 'PromoCodeController');

Route::resource('promocode_service_map', 'PromocodeServiceMapController');

Route::resource('hotel_refund', 'HotelRefundController');

Route::resource('user_refund', 'UserRefundController');


//Route::post('store', ['as' => 'users.store', 'uses' => 'UsersController@store']);

//Route::get('store','\App\Http\Controllers\UsersController@store');
Route::resource('notification', 'NotificationController');


Route::resource('devices', 'DeviceController');
Route::get('razorpay/test', 'RazorPayTestController@testform');
Route::post('razorpay/test', 'RazorPayTestController@submitForm');

Route::any('hotel_refund/refund', ['as' => 'full_refund', 'HotelRefundController@index']);

Route::any('hotel_refund/refund/{id}', 'HotelRefundController@refund');

Route::any('hotel_refund/partial_refund/',  'HotelRefundController@partialRefund');

app/Models/AdminUserLog.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class AdminUserLog
 *
 * @package App\Models
 * @version February 24, 2017, 11:37 am UTC
 */
class AdminUserLog extends Model
{
	use SoftDeletes;

	public $table = 'admin_user_logs';

	const CREATED_AT = 'created_at';
	const UPDATED_AT = 'updated_at';


	protected $dates = ['deleted_at'];


	public $fillable = [
		'log_type' ,
		'user_id' ,
		'action' ,
		'ip' ,
		'latlong'
	];

	/**
	 * The attributes that should be casted to native types.
	 *
	 * @var array
	 */
	protected $casts = [
		'id' => 'integer' ,
		'log_type' => 'integer' ,
		'user_id' => 'integer' ,
		'action' => 'string' ,
		'ip' => 'string' ,
		'latlong' => 'string'
	];

	/**
	 * Validation rules
	 *
	 * @var array
	 */
	public static $rules = [

	];

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 **/
	public function adminLogType ()
	{
		return $this->belongsTo (\App\Models\AdminLogType::class);
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 **/
	public function adminUser ()
	{
		return $this->belongsTo (\App\Models\Admin::class);
	}
}

app/Http/Controllers/AdminUserLogController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\AdminUserLogDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateAdminUserLogRequest;
use App\Http\Requests\UpdateAdminUserLogRequest;
use App\Repositories\AdminUserLogRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class AdminUserLogController extends AppBaseController
{
	/** @var  AdminUserLogRepository */
	private $adminUserLogRepository;

	public function __construct (AdminUserLogRepository $adminUserLogRepo)
	{
		$this->adminUserLogRepository = $adminUserLogRepo;
	}

	/**
	 * Display a listing of the AdminUserLog.
	 *
	 * @param AdminUserLogDataTable $adminUserLogDataTable
	 *
	 * @return Response
	 */
	public function index (AdminUserLogDataTable $adminUserLogDataTable)
	{
		return $adminUserLogDataTable->render ('admin_user_logs.index');
	}

	/**
	 * Show the form for creating a new AdminUserLog.
	 *
	 * @return Response
	 */
	public function create ()
	{
		return view ('admin_user_logs.create');
	}

	/**
	 * Store a newly created AdminUserLog in storage.
	 *
	 * @param CreateAdminUserLogRequest $request
	 *
	 * @return Response
	 */
	public function store (CreateAdminUserLogRequest $request)
	{
		$input = $request->all ();

		$adminUserLog = $this->adminUserLogRepository->create ($input);

		Flash::success ('Admin User Log saved successfully.');

		return redirect (route ('adminUserLogs.index'));
	}

	/**
	 * Display the specified AdminUserLog.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function show ($id)
	{
		$adminUserLog = $this->adminUserLogRepository->findWithoutFail ($id);

		if (empty($adminUserLog)) {
			Flash::error ('Admin User Log not found');

			return redirect (route ('adminUserLogs.index'));
		}

		return view ('admin_user_logs.show')->with ('adminUserLog' , $adminUserLog);
	}

	/**
	 * Show the form for editing the specified AdminUserLog.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function edit ($id)
	{
		$adminUserLog = $this->adminUserLogRepository->findWithoutFail ($id);

		if (empty($adminUserLog)) {
			Flash::error ('Admin User Log not found');

			return redirect (route ('adminUserLogs.index'));
		}

		return view ('admin_user_logs.edit')->with ('adminUserLog' , $adminUserLog);
	}

	/**
	 * Update the specified AdminUserLog in storage.
	 *
	 * @param  int                      $id
	 * @param UpdateAdminUserLogRequest $request
	 *
	 * @return Response
	 */
	public function update ($id , UpdateAdminUserLogRequest $request)
	{
		$adminUserLog = $this->adminUserLogRepository->findWithoutFail ($id);

		if (empty($adminUserLog)) {
			Flash::error ('Admin User Log not found');

			return redirect (route ('adminUserLogs.index'));
		}

		$adminUserLog = $this->adminUserLogRepository->update ($request->all () , $id);

		Flash::success ('Admin User Log updated successfully.');

		return redirect (route ('adminUserLogs.index'));
	}

	/**
	 * Remove the specified AdminUserLog from storage.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function destroy ($id)
	{
		$adminUserLog = $this->adminUserLogRepository->findWithoutFail ($id);

		if (empty($adminUserLog)) {
			Flash::error ('Admin User Log not found');

			return redirect (route ('adminUserLogs.index'));
		}

		$this->adminUserLogRepository->delete ($id);

		Flash::success ('Admin User Log deleted successfully.');

		return redirect (route ('adminUserLogs.index'));
	}
}

resources/views/admin_user_logs/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Admin User Log
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'adminUserLogs.store']) !!}

                    @include('admin_user_logs.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin_user_logs/datatables_actions.blade.php
{!! Form::open(['route' => ['adminUserLogs.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('adminUserLogs.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('adminUserLogs.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/admin_user_logs/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Admin User Log
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::model($adminUserLog, ['route' => ['adminUserLogs.update', $adminUserLog->id], 'method' => 'patch']) !!}

                    @include('admin_user_logs.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin_user_logs/fields.blade.php
<!-- Log Type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('log_type', 'Log Type:') !!}
    {!! Form::number('log_type', null, ['class' => 'form-control']) !!}
</div>

<!-- User Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('user_id', 'User Id:') !!}
    {!! Form::number('user_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Action Field -->
<div class="form-group col-sm-6">
    {!! Form::label('action', 'Action:') !!}
    {!! Form::text('action', null, ['class' => 'form-control']) !!}
</div>

<!-- Ip Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ip', 'Ip:') !!}
    {!! Form::text('ip', null, ['class' => 'form-control']) !!}
</div>

<!-- Latlong Field -->
<div class="form-group col-sm-6">
    {!! Form::label('latlong', 'Latlong:') !!}
    {!! Form::text('latlong', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('adminUserLogs.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/admin_user_logs/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Admin User Logs</h1>
        <h1 class="pull-right">
            <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px"
               href="{!! route('adminUserLogs.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                @include('admin_user_logs.table')
            </div>
        </div>
    </div>
@endsection

resources/views/admin_user_logs/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Admin User Log
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('admin_user_logs.show_fields')
                    <a href="{!! route('adminUserLogs.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin_user_logs/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $adminUserLog->id !!}</p>
</div>

<!-- Log Type Field -->
<div class="form-group">
    {!! Form::label('log_type', 'Log Type:') !!}
    <p>{!! $adminUserLog->log_type !!}</p>
</div>

<!-- User Id Field -->
<div class="form-group">
    {!! Form::label('user_id', 'User Id:') !!}
    <p>{!! $adminUserLog->user_id !!}</p>
</div>

<!-- Action Field -->
<div class="form-group">
    {!! Form::label('action', 'Action:') !!}
    <p>{!! $adminUserLog->action !!}</p>
</div>

<!-- Ip Field -->
<div class="form-group">
    {!! Form::label('ip', 'Ip:') !!}
    <p>{!! $adminUserLog->ip !!}</p>
</div>

<!-- Latlong Field -->
<div class="form-group">
    {!! Form::label('latlong', 'Latlong:') !!}
    <p>{!! $adminUserLog->latlong !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $adminUserLog->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $adminUserLog->updated_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $adminUserLog->deleted_at !!}</p>
</div>

resources/views/admin_user_logs/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection